import type { Metadata } from "next";
import { Barrio } from "next/font/google";
import "./globals.css";


const barrio = Barrio({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-barrio",
});

export const metadata: Metadata = {
  title: "Happy Birthday!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barrio.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
